export const MY_ADDRESS_FETCH_REQUEST = "MY_ADDRESS_FETCH_REQUEST";
export const MY_ADDRESS_FETCH_SUCCESS = "MY_ADDRESS_FETCH_SUCCESS";
export const MY_ADDRESS_FETCH_FAILURE = "MY_ADDRESS_FETCH_FAILURE";